# Generated by Django 4.2.16 on 2026-09-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique institutional ID (e.g. STU-001)', max_length=20, unique=True, verbose_name='Student ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('department', models.CharField(help_text='Academic department name', max_length=100, verbose_name='Department')),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], verbose_name='Academic Year')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text='Include country code if applicable', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(help_text='Full residential or mailing address', verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
    ]
